inherits = "edge_aura"

"ui.background" = { }
"ui.selection" = { bg = "select_blue" }

"ui.cursorline.primary" = { }
"ui.cursorline.secondary" = { }
"ui.cursorcolumn.primary" = { }

"ui.popup" = { fg = "fg", bg = "bg0" }
"ui.popup.info" = { fg = "purple", bg = "bg0" }
"ui.window" = { fg = "fg", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg0" }

"ui.text.info" = { fg = "fg", bg = "bg0" }
"ui.menu" = { fg = "fg", bg = "bg0" }

"ui.virtual.inlay-hint" = { fg = "grey", bg = "bg2" }
"ui.gutter.selected" = {  }
